export { default as DesktopConfigList } from './DesktopConfigList.vue'
export { default as DesktopConfigForm } from './DesktopConfigForm.vue'
export { default as DesktopComponentSelector } from './DesktopComponentSelector.vue'
export { default as CustomDesktopComponent } from './CustomDesktopComponent.vue'
export { default as DesktopView } from './DesktopView.vue'
export { default as DesktopTabsView } from './DesktopTabsView.vue'
export * from './type'