export { default as FileCollectionDetail } from './FileCollectionDetail.vue'
export { default as FileCollectionItem } from './FileCollectionItem.vue'
export { default as FileCollectionRecord } from './FileCollectionRecord.vue'
export { default as FileCollectionRecordList } from './FileCollectionRecordList.vue'
export { default as FileCollectionView } from './FileCollectionView.vue'
export * from './form'